version: '3.8'
services:
  academicservice:
    image: my_image_academicservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - my_network

  notafrequenciaservice:
    image: my_image_notafrequenciaservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - my_network

  atividadeextracurricularservice:
    image: my_image_atividadeextracurricularservice
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    networks:
      - my_network
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  my_network:
