spring:
  cloud:
    gateway:
      routes:
        - id: academic-service
          uri: http://localhost:8081
          predicates:
            - Path=/academic/**
        - id: atividadeExtraCurricular-service
          uri: http://localhost:8082
          predicates:
            - Path=/atividade/**
        - id: notaFrequencia-service
          uri: http://localhost:8083
          predicates:
            - Path=/notafrequencia/**
        - id: authService
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**
