version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=academics_db
      - MYSQL_USER=academics_user
      - MYSQL_PASSWORD=Academics@Secure123
      - MYSQL_ROOT_PASSWORD=Root@Secure123
    ports:
      - "3306:3306"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

  api-gateway:
    build: ./api-gateway
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"

  academic-service:
    build: ./academic-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8081"

  atividade-extracurricular-service:
    build: ./atividadeExtraCurricular-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"

  auth-service:
    build: ./auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8083:8083"

  nota-frequencia-service:
    build: ./notaFrequencia-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - rabbitmq
    ports:
      - "8084:8084"
