version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=academics_db
      - POSTGRES_USER=academics_user
      - POSTGRES_PASSWORD=Academics@Secure123
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "15672:15672"
      - "5672:5672"

  api-gateway:
    build: ./api-gateway
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    command: /bin/sh -c "mvn clean package && java -jar target/api-gateway-0.0.1-SNAPSHOT.jar"

  academic-service:
    build: ./academic-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8081"
    command: mvn clean package

  atividade-extracurricular-service:
    build: ./atividadeExtraCurricular-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"
    command: mvn clean package

  nota-frequencia-service:
    build: ./notaFrequencia-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/academics_db
      - SPRING_DATASOURCE_USERNAME=academics_user
      - SPRING_DATASOURCE_PASSWORD=Academics@Secure123
    depends_on:
      - rabbitmq
    ports:
      - "8083:8083"
    command: mvn clean package